
name: 'Check Existing Tag'
inputs:
  tag:
    description: 'Tag'
    required: true
outputs:
  tag_is_present:
    description: 'True/False'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.tag }}
