
name: 'Check Existing Tag Action'
description: 'Call GH API and check if action input tag is present as a valid tag in current repo'
inputs:
  tag:
    description: 'Tag'
    required: true
outputs:
  tag_is_present:
    description: 'True/False'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.tag }}
